spring:
  datasource:
    username: root
    password: P@$$w0rd
    url: jdbc:mysql://localhost:3306/angular
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9001
  servlet:
    context-path: /angularapi
  